services:
  postgres_db:
    image: postgres
    env_file: ./.env
    # wait for postgres to be ready before starting
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    build: ./frontend/
    env_file: ./frontend/.env
    ports:
      - "3001:3001"
    depends_on:
      - backend
